
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyTiecCuoi.Model
{

using System;
    using System.Collections.Generic;
    
public partial class BAOCAOTHANG
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BAOCAOTHANG()
    {

        this.BAOCAONGAYs = new HashSet<BAOCAONGAY>();

    }


    public int MaBaoCaoThang { get; set; }

    public int Thang { get; set; }

    public int Nam { get; set; }

    public decimal TongDoanhThu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BAOCAONGAY> BAOCAONGAYs { get; set; }

}

}
