
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyTiecCuoi.Model
{

using System;
    using System.Collections.Generic;
    
public partial class DICHVU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DICHVU()
    {

        this.PHIEUDATDICHVUs = new HashSet<PHIEUDATDICHVU>();

    }


    public int MaDichVu { get; set; }

    public string TenDichVu { get; set; }

    public decimal DonGia { get; set; }

    public string MoTa { get; set; }

    public string HinhAnh { get; set; }

    public string GhiChu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEUDATDICHVU> PHIEUDATDICHVUs { get; set; }

}

}
