
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyTiecCuoi.Model
{

using System;
    using System.Collections.Generic;
    
public partial class HOADON
{

    public int MaHoaDon { get; set; }

    public decimal TongTienBan { get; set; }

    public decimal TongTienDichVu { get; set; }

    public decimal TongTienHoaDon { get; set; }

    public decimal ConLai { get; set; }

    public System.DateTime NgayThanhToan { get; set; }

    public int MaTiecCuoi { get; set; }



    public virtual TIECCUOI TIECCUOI { get; set; }

}

}
