
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyTiecCuoi.Model
{

using System;
    using System.Collections.Generic;
    
public partial class LOAISANH
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LOAISANH()
    {

        this.SANHs = new HashSet<SANH>();

    }


    public int MaLoaiSanh { get; set; }

    public string TenLoaiSanh { get; set; }

    public decimal DonGiaBanToiThieu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SANH> SANHs { get; set; }

}

}
