
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyTiecCuoi.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PHIEUDATBAN
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PHIEUDATBAN()
    {

        this.CT_PHIEUDATBAN = new HashSet<CT_PHIEUDATBAN>();

    }


    public int MaPhieuDatBan { get; set; }

    public int MaTiecCuoi { get; set; }

    public string LoaiBan { get; set; }

    public int SoLuong { get; set; }

    public int SoLuongDuTru { get; set; }

    public decimal DonGiaBan { get; set; }

    public string GhiChu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CT_PHIEUDATBAN> CT_PHIEUDATBAN { get; set; }

    public virtual TIECCUOI TIECCUOI { get; set; }

}

}
