
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLyTiecCuoi.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PHIEUDATDICHVU
{

    public int MaTiecCuoi { get; set; }

    public int MaDichVu { get; set; }

    public int SoLuong { get; set; }

    public decimal ThanhTien { get; set; }

    public string GhiChu { get; set; }



    public virtual DICHVU DICHVU { get; set; }

    public virtual TIECCUOI TIECCUOI { get; set; }

}

}
